services:
  - type: web
    name: ai-backend
    env: python
    region: oregon
    rootDir: backend
    buildCommand: pip install -r ../requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_API_KEY
        sync: false
    plan: free

  - type: web
    name: ai-frontend
    env: static
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
    plan: free
