services:
  - type: web
    name: ai-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_API_KEY
        sync: false
    plan: free

  - type: static
    name: ai-frontend
    buildCommand: ""
    publishPath: frontend
    plan: free
